//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodInventory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POS_InventoryEntities : DbContext
    {
        public POS_InventoryEntities()
            : base("name=POS_InventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Sales_Detail> Sales_Detail { get; set; }
        public virtual DbSet<Salespersondetail> Salespersondetails { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
    }
}
